for (let alunos = 1; alunos <= 10; alunos++){
    console.log(`tinha ${alunos}  aluno na sala de aula`)
}


let chocolates = 10
while (1 <= chocolates){
    console.log(`${chocolates} chocolates foram usados`)
    chocolates--
}


let book = 1
while (book <= 100){
    console.log(`os números books usados é ${book}`)
    book+=2
}

for (bombons = 1; bombons <= 100; bombons+=2){
    console.log(`foram ${bombons} bomobns distribuídos`)
}



let canetinhas = 0
while (canetinhas <= 100){
    console.log(`canetinhas que forom colocado no carrinho é igual a ${canetinhas}`)
    canetinhas+=2
}

for (mochilas = 0; mochilas<= 100; mochilas+=2){
    console.log(`${mochilas} é a quantidade de mochilas entregues aos alunos`)
}


